### PR TITLE
Update bower.json and Gruntfile.js

### PR DESCRIPTION
**Pull request by johanbove**
Fixing issue #5

### CODE REVIEW

**Comment by ozasadnyy** [comment]
@johanbove Thanks for PR. Will It paste SVG data for every image? Because if somebody are using svg images for sponsors or another logo it will reduce performance dramatically.

**Comment by johanbove** [comment]
The svg4everybody script will lookup SVG tags which have the "use" tag and reference to external xlink:href source files. So "normal" logo SVGs are not involved in the parse so I believe the performance impact will be limited. But I have not tested it myself beyond the original "icon sprites" as included in the template.

See the source at https://github.com/jonathantneal/svg4everybody/blob/master/svg4everybody.js :

```
document.getElementsByTagName('use')
```

**Comment by erickmendonca** [comment]
Last year we had a similar issue on the DevFest Nordeste (Brazil) website, forked from the original zeppelin.

**Comment by ozasadnyy** [comment]
@johanbove then it should work. Thanks again for contributing!

**Pull request merged**
